// bankData.jsx
export const bankData = {
    JPMorganChase: [
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$180', balance: '$7378.88' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$210', balance: '$6800.87' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$240', balance: '$7275.60' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$270', balance: '$7668.17' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$300', balance: '$6028.85' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$330', balance: '$6652.59' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$360', balance: '$6194.94' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$180', balance: '$7247.24' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$390', balance: '$7801.55' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$420', balance: '$7773.36' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$450', balance: '$6762.90' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$480', balance: '$7179.18' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$510', balance: '$6924.18' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$540', balance: '$8154.54' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$570', balance: '$9607.20' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$600', balance: '$10725.66' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$630', balance: '$7724.67' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$660', balance: '$13244.23' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$690', balance: '$8249.18' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$720', balance: '$39862.85' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$750', balance: '$8844.83' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$780', balance: '$14837.68' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$810', balance: '$9008.84' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$840', balance: '$46624.52' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$870', balance: '$11028.87' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$900', balance: '$8212.29' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$930', balance: '$9205.42' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$960', balance: '$10891.56' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$990', balance: '$11339.63' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1020', balance: '$13713.60' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1050', balance: '$11098.71' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1080', balance: '$7523.61' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1110', balance: '$38966.10' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1140', balance: '$8490.49' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1170', balance: '$8203.50' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1200', balance: '$14073.82' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1230', balance: '$12830.70' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1260', balance: '$8883.27' },
    ],
    WellsFargo: [
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$180', balance: '$8000.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$210', balance: '$8200.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$240', balance: '$8400.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$270', balance: '$8600.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$300', balance: '$8800.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$330', balance: '$9000.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$360', balance: '$9200.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$180', balance: '$7247.24' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$210', balance: '$6663.48' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$240', balance: '$7800.49' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$270', balance: '$7464.75' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$300', balance: '$6796.32' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$330', balance: '$6192.73' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$360', balance: '$6132.65' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$390', balance: '$7801.55' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$420', balance: '$7773.36' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$450', balance: '$6762.90' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$480', balance: '$7179.18' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$510', balance: '$6924.18' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$540', balance: '$8154.54' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$570', balance: '$9607.20' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$600', balance: '$10725.66' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$630', balance: '$7724.67' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$660', balance: '$13244.23' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$690', balance: '$8249.18' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$720', balance: '$39862.85' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$750', balance: '$8844.83' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$780', balance: '$14837.68' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$810', balance: '$9008.84' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$840', balance: '$46624.52' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$870', balance: '$11028.87' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$900', balance: '$8212.29' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$930', balance: '$9205.42' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$960', balance: '$10891.56' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$990', balance: '$11339.63' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1020', balance: '$13713.60' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1050', balance: '$11098.71' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1080', balance: '$7523.61' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1110', balance: '$38966.10' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1140', balance: '$8490.49' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1170', balance: '$8203.50' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1200', balance: '$14073.82' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1230', balance: '$12830.70' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1260', balance: '$8883.27' },
        
    ],
    BankOfAmerica: [
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$180', balance: '$7247.24' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$210', balance: '$6663.48' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$240', balance: '$7800.49' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$270', balance: '$7464.75' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$300', balance: '$6796.32' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$330', balance: '$6192.73' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$360', balance: '$6132.65' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$390', balance: '$7801.55' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$420', balance: '$7773.36' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$450', balance: '$6762.90' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$480', balance: '$7179.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$510', balance: '$6924.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$540', balance: '$8154.54' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$570', balance: '$9607.20' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$600', balance: '$10725.66' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$630', balance: '$7724.67' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$660', balance: '$13244.23' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$690', balance: '$8249.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$720', balance: '$39862.85' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$750', balance: '$8844.83' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$780', balance: '$14837.68' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$810', balance: '$9008.84' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$840', balance: '$46624.52' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$870', balance: '$11028.87' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$900', balance: '$8212.29' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$930', balance: '$9205.42' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$960', balance: '$10891.56' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$990', balance: '$11339.63' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1020', balance: '$13713.60' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1050', balance: '$11098.71' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1080', balance: '$7523.61' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1110', balance: '$38966.10' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1140', balance: '$8490.49' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1170', balance: '$8203.50' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1200', balance: '$14073.82' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1230', balance: '$12830.70' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1260', balance: '$8883.27' },
    ],
};
