// bankData.jsx
export const bankData = {
    JPMorganChase: [
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$386', balance: '$7378.88' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$367', balance: '$6800.87' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$383', balance: '$7275.60' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$396', balance: '$7668.17' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$341', balance: '$6028.85' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$362', balance: '$6652.59' },
        { bank: 'JPMorgan Chase & Co', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$347', balance: '$6194.94' },
    ],
    WellsFargo: [
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$400', balance: '$8000.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$410', balance: '$8200.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$420', balance: '$8400.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$430', balance: '$8600.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$440', balance: '$8800.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$450', balance: '$9000.00' },
        { bank: 'Wells Fargo', desc: 'CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$460', balance: '$9200.00' },
    ],
    BankOfAmerica: [
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$382', balance: '$7247.24' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$363', balance: '$6663.48' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$400', balance: '$7800.49' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$389', balance: '$7464.75' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$367', balance: '$6796.32' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$347', balance: '$6192.73' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$345', balance: '$6132.65' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$401', balance: '$7801.55' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$400', balance: '$7773.36' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$366', balance: '$6762.90' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$380', balance: '$7179.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$371', balance: '$6924.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$412', balance: '$8154.54' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$461', balance: '$9607.20' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$573', balance: '$10725.66' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$398', balance: '$7724.67' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$825', balance: '$13244.23' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$415', balance: '$8249.18' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1348', balance: '$39862.85' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$435', balance: '$8844.83' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$984', balance: '$14837.68' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$401', balance: '$9008.84' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1383', balance: '$46624.52' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$603', balance: '$11028.87' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$414', balance: '$8212.29' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$421', balance: '$9205.42' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$590', balance: '$10891.56' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$634', balance: '$11339.63' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$872', balance: '$13713.60' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$610', balance: '$11098.71' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$391', balance: '$7523.61' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1330', balance: '$38966.10' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$423', balance: '$8490.49' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$414', balance: '$8203.50' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$908', balance: '$14073.82' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$783', balance: '$12830.85' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1144', balance: '$17914.95' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$580', balance: '$10495.52' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$367', balance: '$6884.25' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$361', balance: '$6758.15' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$374', balance: '$6899.16' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$569', balance: '$10544.94' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$748', balance: '$12945.00' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$698', balance: '$11421.76' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1347', balance: '$24168.63' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$695', balance: '$11907.67' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1175', balance: '$18733.93' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$768', balance: '$13325.68' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$908', balance: '$14732.75' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$594', balance: '$11509.53' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$653', balance: '$12491.59' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$633', balance: '$11371.96' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$352', balance: '$6821.47' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$518', balance: '$10246.80' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$471', balance: '$9323.71' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$555', balance: '$11647.09' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$751', balance: '$13676.72' },
        { bank: 'Bank of America Corp', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$647', balance: '$12217.54' },
    ],
    CitigroupInc: [
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$360", balance: "$6575.86" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$395", balance: "$7624.44" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$383", balance: "$7276.77" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$398", balance: "$7721.83" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$395", balance: "$7641.75" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$390", balance: "$7500.81" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$387", balance: "$7391.55" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$350", balance: "$6272.72" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$958", balance: "$14574.52" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$405", balance: "$7921.45" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$682", balance: "$11813.90" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1208", balance: "$30363.66" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$480", balance: "$9799.40" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$500", balance: "$9999.46" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$495", balance: "$9942.42" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$434", balance: "$8808.44" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$958", balance: "$14579.98" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$420", balance: "$8394.61" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$374", balance: "$7007.63" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$384", balance: "$7297.78" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$607", balance: "$11068.79" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$381", balance: "$7225.55" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$417", balance: "$8303.89" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$887", balance: "$13870.82" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1316", balance: "$38284.65" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$628", balance: "$11272.45" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$695", balance: "$11950.52" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$400", balance: "$7777.60" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$833", balance: "$13324.60" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$437", balance: "$8902.18" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$412", balance: "$8144.15" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$403", balance: "$7889.77" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1338", balance: "$39394.55" },
        { bank: "Citigroup Inc", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$640", balance: "$11392.70" }
      ],

      ChimeBank: [
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$342", balance: "$6044.31" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$370", balance: "$6876.29" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$371", balance: "$6928.45" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$347", balance: "$6199.15" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$397", balance: "$7703.25" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$375", balance: "$7047.13" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$405", balance: "$7943.69" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$374", balance: "$7013.26" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$398", balance: "$7725.54" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$405", balance: "$7929.79" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$905", balance: "$14043.58" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$402", balance: "$7857.35" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$645", balance: "$11442.11" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$559", balance: "$10583.89" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1382", balance: "$44084.33" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$394", balance: "$7599.79" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$382", balance: "$7247.98" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1263", balance: "$35633.52" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$494", balance: "$9934.71" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1387", balance: "$46812.28" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$413", balance: "$8179.12" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$428", balance: "$8628.85" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$386", balance: "$7353.85" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$565", balance: "$10645.39" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$438", balance: "$8922.34" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$398", balance: "$7728.31" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1042", balance: "$15413.38" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$440", balance: "$9394.96" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$412", balance: "$9116.47" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$423", balance: "$8479.16" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$545", balance: "$10444.90" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$416", balance: "$8255.54" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$908", balance: "$14072.43" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$622", balance: "$11211.85" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$593", balance: "$10924.80" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$530", balance: "$10292.65" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$404", balance: "$7891.51" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$383", balance: "$7281.22" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1061", balance: "$15608.63" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$1411", balance: "$48008.90" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$723", balance: "$12229.60" },
        { "bank": "Chime Bank", desc: "SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS", price: "$435", balance: "$8843.20" }
    ], 
    
    HuntingtonBank: [
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$353', balance: '$6373.56' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$379', balance: '$7162.33' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$395', balance: '$7623.61' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$357', balance: '$6496.65' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$400', balance: '$7800.54' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$384', balance: '$7303.69' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$368', balance: '$6812.13' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$381', balance: '$7203.31' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$349', balance: '$6246.72' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1285', balance: '$34230.97' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$503', balance: '$10029.49' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$377', balance: '$7105.74' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$379', balance: '$7161.88' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$432', balance: '$8738.78' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$751', balance: '$12510.86' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$636', balance: '$11353.67' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$744', balance: '$12440.59' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$635', balance: '$11346.47' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$505', balance: '$10045.58' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$400', balance: '$7796.83' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$680', balance: '$11795.31' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$401', balance: '$7804.93' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$391', balance: '$7515.74' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$550', balance: '$10497.43' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$418', balance: '$8319.18' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1359', balance: '$42948.37' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1015', balance: '$15142.56' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$437', balance: '$8882.21' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$460', balance: '$9593.83' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$1371', balance: '$46039.71' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$426', balance: '$8555.40' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$743', balance: '$12426.47' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$643', balance: '$11423.91' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$678', balance: '$11780.55' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$435', balance: '$8836.36' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$343', balance: '$6069.34' },
        { bank: 'Huntington Bank', desc: 'SAVINGS + CHECKINGS + INFO + EMAIL LOGIN PASS', price: '$379', balance: '$7141.80' },
      ]      
  };
  